CREATE DATABASE GENERIC;

CREATE TABLE [dbo].[TB_USERS](
[USER_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
[USER_NAME] VARCHAR(max) NOT NULL,
[USER_CPF] VARCHAR(max) NOT NULL,
[USER_DATE] DATETIME NOT NULL,
[USER_USERNAME] VARCHAR(15) NOT NULL,
[USER_PASSWORD] VARCHAR(max) NOT NULL,
)

CREATE TABLE [dbo].[TB_CATEGORY](
[CAT_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
[CAT_NAME] VARCHAR(max) NOT NULL,
)

CREATE TABLE [dbo].[TB_PRODUCT](
[PROD_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
[PROD_NAME] VARCHAR(max) NOT NULL,
[PROD_PHOTO] VARCHAR(max),
[PROD_PRICE] DECIMAL,
[PROD_IDCATEGORY] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TB_CATEGORY (CAT_ID)
)

CREATE TABLE [dbo].[TB_ORDER](
[ORD_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
[ORD_NAME] VARCHAR(max) NOT NULL,
[ORD_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
[ORD_STATUS] BIT default 0,
)

CREATE TABLE [dbo].[TB_REQUEST](
[REQ_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
[REQ_DATE] DATETIME NOT NULL DEFAULT GETDATE(),
[REQ_IDORDER] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TB_ORDER (ORD_ID),
[REQ_IDPRODUCT] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [TB_PRODUCT] (PROD_ID),
[REQ_QUANTITY] INT DEFAULT 1
)
